# Processing Numerical Data

Specifically scaling.  I'm just showing how scaling works on the 2 numerical columns in the t-shirt dataset.  In reality, you would convert the catagorical features into ordinal and nominal values and then scale all columns.

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
import pandas as pd
import numpy as np

# Display all cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

from IPython import get_ipython
ipython = get_ipython()

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

# Set max rows and columns displayed in jupyter
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

## Load our t-shirts
Uh-oh.  utils.py is no longer in this directory.  How do we get to it?  Simple make utils a package and import it. See course website '41_create_an_importable_package.pdf' in week 4.

In [2]:
import sys
sys.path

['C:\\Users\\ereno\\anaconda3\\python313.zip',
 'C:\\Users\\ereno\\anaconda3\\DLLs',
 'C:\\Users\\ereno\\anaconda3\\Lib',
 'C:\\Users\\ereno\\anaconda3',
 '',
 'C:\\Users\\ereno\\anaconda3\\Lib\\site-packages',
 'C:\\Users\\ereno\\anaconda3\\Lib\\site-packages\\win32',
 'C:\\Users\\ereno\\anaconda3\\Lib\\site-packages\\win32\\lib',
 'C:\\Users\\ereno\\anaconda3\\Lib\\site-packages\\Pythonwin']

In [4]:
# I need to add the parent directory of utils in order to find it
#it happens to be up 1 directory.
import os
import sys
PROJECT_ROOT = os.path.abspath(os.path.join(
                  os.getcwd(),
                  os.pardir)
)

#only add it once
# if (PROJECT_ROOT not in sys.path):
#     sys.path.append(PROJECT_ROOT)

In [5]:
import utils as ut
df = ut.generate_tshirt_order()
df

         weight t_shirt_size t_shirt_color                 name
0    104.902367        small        orange          Kerry Weber
1    128.006126        small         green    Gabriel Millhouse
2     97.726483        small          blue      William Woodall
3    108.066307        small         black  Elizabeth Gallagher
4    126.468008        small        orange    Christine Garland
..          ...          ...           ...                  ...
295  188.447611        large         green          Jean Warden
296  169.199903        large        orange        Michael Byers
297  145.682562        large          blue         John Maberry
298  169.968276        large          blue         Mike Johnson
299  151.844047        large         black       John Pensinger

[300 rows x 4 columns]

## Use dtypes to see the kinds of processing we will need

In [6]:
df.dtypes

weight           float64
t_shirt_size      object
t_shirt_color     object
name              object
dtype: object

In [7]:
df.nunique()

weight           300
t_shirt_size       3
t_shirt_color      5
name             300
dtype: int64

## weight and age are numerical, lets go ahead and scale them
first using min-max encoding<br>
And then using standardization<br><br>

In [8]:
#these are the numerical features to transform for now
feats=['weight','Age']

### min max scaler

In [9]:
#make copy so we can use original for standard scaler
df1=df.copy()

In [13]:
from sklearn.preprocessing import MinMaxScaler
available_feats = [feat for feat in feats if feat in df1.columns]
df1[available_feats] = MinMaxScaler().fit_transform(df1[available_feats])

In [14]:
df1.describe()

           weight
count  300.000000
mean     0.369841
std      0.200613
min      0.000000
25%      0.221095
50%      0.348164
75%      0.493825
max      1.000000

### standard scaler (subtract mean/divide by std)

In [15]:
from sklearn.preprocessing import StandardScaler
df[feats]=StandardScaler().fit_transform(df[feats])

KeyError: "['Age'] not in index"

In [16]:
df.describe()

             weight           Age
count  3.000000e+02  3.000000e+02
mean   3.789561e-16 -2.250052e-16
std    1.001671e+00  1.001671e+00
min   -1.894320e+00 -1.565795e+00
25%   -8.026231e-01 -8.942604e-01
50%   -1.071779e-01  1.130417e-01
75%    6.625061e-01  8.685182e-01
max    2.678005e+00  1.456111e+00